### ISSUE TITLE
undefined symbol: TLS_client_method

### ISSUE THREAD

**Issue by oberman** [snowflakedb/pdo_snowflake#198]
I'm on an AWS Linux AMI box and did:
```
git clone https://github.com/snowflakedb/pdo_snowflake.git
cd pdo_snowflake
export PHP_HOME=/usr
./scripts/build_pdo_snowflake.sh
```

The build process seems fine.  I'll paste below.  But when I run PHP get the error from the subject in /var/log/messages 
```
php: PHP Warning:  PHP Startup: Unable to load dynamic library 'modules/pdo_snowflake.so' (tried: modules/pdo_snowflake.so (modules/pdo_snowflake.so: undefined symbol: TLS_client_method), /usr/lib64/php/7.2/modules/modules/pdo_snowflake.so.so (/usr/lib64/php/7.2/modules/modules/pdo_snowflake.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```

```
./scripts/build_pdo_snowflake.sh
find . -name \*.gcno -o -name \*.gcda | xargs rm -f
find . -name \*.lo -o -name \*.o | xargs rm -f
find . -name \*.la -o -name \*.a | xargs rm -f
find . -name \*.so | xargs rm -f
find . -name .libs -a -type d|xargs rm -rf
rm -f libphp.la       modules/* libs/*
Configuring for:
PHP Api Version:         20170718
Zend Module Api No:      20170718
Zend Extension Api No:   320170718
./configure --enable-pdo_snowflake
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /usr
checking for PHP includes... -I/usr/include/php/7.2/php -I/usr/include/php/7.2/php/main -I/usr/include/php/7.2/php/TSRM -I/usr/include/php/7.2/php/Zend -I/usr/include/php/7.2/php/ext -I/usr/include/php/7.2/php/ext/date/lib
checking for PHP extension directory... /usr/lib64/php/7.2/modules
checking for PHP installed headers prefix... /usr/include/php/7.2/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... gawk
checking for Snowflake DB support for PDO... yes, shared
checking whether to include code coverage symbols... no
checking for libsnowflakeclient files in default path... found in libsnowflakeclient
checking how to print strings... printf
checking for a sed that does not truncate output... (cached) /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by cc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking for gawk... (cached) gawk
checking command to parse /usr/bin/nm -B output from cc object... failed
checking for sysroot... no
checking for mt... no
checking if : is a manifest tool... no
checking for ANSI C header files... no
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC -DPIC
checking if cc PIC flag -fPIC -DPIC works... yes
checking if cc static flag -static works... no
checking if cc supports -c -o file.o... yes
checking if cc supports -c -o file.o... (cached) yes
checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
configure: creating ./config.status
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing libtool commands
/bin/sh /cshome/will/pdo_snowflake/libtool --mode=compile cc -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/cshome/will/pdo_snowflake -DPHP_ATOM_INC -I/cshome/will/pdo_snowflake/include -I/cshome/will/pdo_snowflake/main -I/cshome/will/pdo_snowflake -I/usr/include/php/7.2/php -I/usr/include/php/7.2/php/main -I/usr/include/php/7.2/php/TSRM -I/usr/include/php/7.2/php/Zend -I/usr/include/php/7.2/php/ext -I/usr/include/php/7.2/php/ext/date/lib -I/cshome/will/pdo_snowflake/libsnowflakeclient/include  -DHAVE_CONFIG_H  -std=c99 -Werror -g -O2   -c /cshome/will/pdo_snowflake/pdo_snowflake.c -o pdo_snowflake.lo
libtool: compile:  cc -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/cshome/will/pdo_snowflake -DPHP_ATOM_INC -I/cshome/will/pdo_snowflake/include -I/cshome/will/pdo_snowflake/main -I/cshome/will/pdo_snowflake -I/usr/include/php/7.2/php -I/usr/include/php/7.2/php/main -I/usr/include/php/7.2/php/TSRM -I/usr/include/php/7.2/php/Zend -I/usr/include/php/7.2/php/ext -I/usr/include/php/7.2/php/ext/date/lib -I/cshome/will/pdo_snowflake/libsnowflakeclient/include -DHAVE_CONFIG_H -std=c99 -Werror -g -O2 -c /cshome/will/pdo_snowflake/pdo_snowflake.c  -fPIC -DPIC -o .libs/pdo_snowflake.o
/bin/sh /cshome/will/pdo_snowflake/libtool --mode=compile cc -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/cshome/will/pdo_snowflake -DPHP_ATOM_INC -I/cshome/will/pdo_snowflake/include -I/cshome/will/pdo_snowflake/main -I/cshome/will/pdo_snowflake -I/usr/include/php/7.2/php -I/usr/include/php/7.2/php/main -I/usr/include/php/7.2/php/TSRM -I/usr/include/php/7.2/php/Zend -I/usr/include/php/7.2/php/ext -I/usr/include/php/7.2/php/ext/date/lib -I/cshome/will/pdo_snowflake/libsnowflakeclient/include  -DHAVE_CONFIG_H  -std=c99 -Werror -g -O2   -c /cshome/will/pdo_snowflake/snowflake_driver.c -o snowflake_driver.lo
libtool: compile:  cc -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/cshome/will/pdo_snowflake -DPHP_ATOM_INC -I/cshome/will/pdo_snowflake/include -I/cshome/will/pdo_snowflake/main -I/cshome/will/pdo_snowflake -I/usr/include/php/7.2/php -I/usr/include/php/7.2/php/main -I/usr/include/php/7.2/php/TSRM -I/usr/include/php/7.2/php/Zend -I/usr/include/php/7.2/php/ext -I/usr/include/php/7.2/php/ext/date/lib -I/cshome/will/pdo_snowflake/libsnowflakeclient/include -DHAVE_CONFIG_H -std=c99 -Werror -g -O2 -c /cshome/will/pdo_snowflake/snowflake_driver.c  -fPIC -DPIC -o .libs/snowflake_driver.o
/bin/sh /cshome/will/pdo_snowflake/libtool --mode=compile cc -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/cshome/will/pdo_snowflake -DPHP_ATOM_INC -I/cshome/will/pdo_snowflake/include -I/cshome/will/pdo_snowflake/main -I/cshome/will/pdo_snowflake -I/usr/include/php/7.2/php -I/usr/include/php/7.2/php/main -I/usr/include/php/7.2/php/TSRM -I/usr/include/php/7.2/php/Zend -I/usr/include/php/7.2/php/ext -I/usr/include/php/7.2/php/ext/date/lib -I/cshome/will/pdo_snowflake/libsnowflakeclient/include  -DHAVE_CONFIG_H  -std=c99 -Werror -g -O2   -c /cshome/will/pdo_snowflake/snowflake_stmt.c -o snowflake_stmt.lo
libtool: compile:  cc -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/cshome/will/pdo_snowflake -DPHP_ATOM_INC -I/cshome/will/pdo_snowflake/include -I/cshome/will/pdo_snowflake/main -I/cshome/will/pdo_snowflake -I/usr/include/php/7.2/php -I/usr/include/php/7.2/php/main -I/usr/include/php/7.2/php/TSRM -I/usr/include/php/7.2/php/Zend -I/usr/include/php/7.2/php/ext -I/usr/include/php/7.2/php/ext/date/lib -I/cshome/will/pdo_snowflake/libsnowflakeclient/include -DHAVE_CONFIG_H -std=c99 -Werror -g -O2 -c /cshome/will/pdo_snowflake/snowflake_stmt.c  -fPIC -DPIC -o .libs/snowflake_stmt.o
/bin/sh /cshome/will/pdo_snowflake/libtool --mode=compile cc -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/cshome/will/pdo_snowflake -DPHP_ATOM_INC -I/cshome/will/pdo_snowflake/include -I/cshome/will/pdo_snowflake/main -I/cshome/will/pdo_snowflake -I/usr/include/php/7.2/php -I/usr/include/php/7.2/php/main -I/usr/include/php/7.2/php/TSRM -I/usr/include/php/7.2/php/Zend -I/usr/include/php/7.2/php/ext -I/usr/include/php/7.2/php/ext/date/lib -I/cshome/will/pdo_snowflake/libsnowflakeclient/include  -DHAVE_CONFIG_H  -std=c99 -Werror -g -O2   -c /cshome/will/pdo_snowflake/snowflake_arraylist.c -o snowflake_arraylist.lo
libtool: compile:  cc -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/cshome/will/pdo_snowflake -DPHP_ATOM_INC -I/cshome/will/pdo_snowflake/include -I/cshome/will/pdo_snowflake/main -I/cshome/will/pdo_snowflake -I/usr/include/php/7.2/php -I/usr/include/php/7.2/php/main -I/usr/include/php/7.2/php/TSRM -I/usr/include/php/7.2/php/Zend -I/usr/include/php/7.2/php/ext -I/usr/include/php/7.2/php/ext/date/lib -I/cshome/will/pdo_snowflake/libsnowflakeclient/include -DHAVE_CONFIG_H -std=c99 -Werror -g -O2 -c /cshome/will/pdo_snowflake/snowflake_arraylist.c  -fPIC -DPIC -o .libs/snowflake_arraylist.o
/bin/sh /cshome/will/pdo_snowflake/libtool --mode=link cc -DPHP_ATOM_INC -I/cshome/will/pdo_snowflake/include -I/cshome/will/pdo_snowflake/main -I/cshome/will/pdo_snowflake -I/usr/include/php/7.2/php -I/usr/include/php/7.2/php/main -I/usr/include/php/7.2/php/TSRM -I/usr/include/php/7.2/php/Zend -I/usr/include/php/7.2/php/ext -I/usr/include/php/7.2/php/ext/date/lib -I/cshome/will/pdo_snowflake/libsnowflakeclient/include  -DHAVE_CONFIG_H  -std=c99 -Werror -g -O2  -fPIC -Wl,--whole-archive libsnowflakeclient/lib/linux/libsnowflakeclient.a libsnowflakeclient/deps-build/linux/openssl/lib/libcrypto.a libsnowflakeclient/deps-build/linux/openssl/lib/libssl.a libsnowflakeclient/deps-build/linux/curl/lib/libcurl.a libsnowflakeclient/deps-build/linux/aws/lib64/libaws-cpp-sdk-core.a libsnowflakeclient/deps-build/linux/aws/lib64/libaws-cpp-sdk-s3.a libsnowflakeclient/deps-build/linux/azure/lib/libazure-storage-lite.a -Wl,--no-whole-archive -o pdo_snowflake.la -export-dynamic -avoid-version -prefer-pic -module -rpath /cshome/will/pdo_snowflake/modules  pdo_snowflake.lo snowflake_driver.lo snowflake_stmt.lo snowflake_arraylist.lo

*** Warning: Linking the shared library pdo_snowflake.la against the
*** static library libsnowflakeclient/lib/linux/libsnowflakeclient.a is not portable!

*** Warning: Linking the shared library pdo_snowflake.la against the
*** static library libsnowflakeclient/deps-build/linux/openssl/lib/libcrypto.a is not portable!

*** Warning: Linking the shared library pdo_snowflake.la against the
*** static library libsnowflakeclient/deps-build/linux/openssl/lib/libssl.a is not portable!

*** Warning: Linking the shared library pdo_snowflake.la against the
*** static library libsnowflakeclient/deps-build/linux/curl/lib/libcurl.a is not portable!

*** Warning: Linking the shared library pdo_snowflake.la against the
*** static library libsnowflakeclient/deps-build/linux/aws/lib64/libaws-cpp-sdk-core.a is not portable!

*** Warning: Linking the shared library pdo_snowflake.la against the
*** static library libsnowflakeclient/deps-build/linux/aws/lib64/libaws-cpp-sdk-s3.a is not portable!

*** Warning: Linking the shared library pdo_snowflake.la against the
*** static library libsnowflakeclient/deps-build/linux/azure/lib/libazure-storage-lite.a is not portable!
libtool: link: cc -shared  -fPIC -DPIC  .libs/pdo_snowflake.o .libs/snowflake_driver.o .libs/snowflake_stmt.o .libs/snowflake_arraylist.o   libsnowflakeclient/lib/linux/libsnowflakeclient.a libsnowflakeclient/deps-build/linux/openssl/lib/libcrypto.a libsnowflakeclient/deps-build/linux/openssl/lib/libssl.a libsnowflakeclient/deps-build/linux/curl/lib/libcurl.a libsnowflakeclient/deps-build/linux/aws/lib64/libaws-cpp-sdk-core.a libsnowflakeclient/deps-build/linux/aws/lib64/libaws-cpp-sdk-s3.a libsnowflakeclient/deps-build/linux/azure/lib/libazure-storage-lite.a  -O2 -Wl,--whole-archive -Wl,--no-whole-archive   -Wl,-soname -Wl,pdo_snowflake.so -o .libs/pdo_snowflake.so
libtool: link: ( cd ".libs" && rm -f "pdo_snowflake.la" && ln -s "../pdo_snowflake.la" "pdo_snowflake.la" )
/bin/sh /cshome/will/pdo_snowflake/libtool --mode=install cp ./pdo_snowflake.la /cshome/will/pdo_snowflake/modules
libtool: install: cp ./.libs/pdo_snowflake.so /cshome/will/pdo_snowflake/modules/pdo_snowflake.so
libtool: install: cp ./.libs/pdo_snowflake.lai /cshome/will/pdo_snowflake/modules/pdo_snowflake.la
libtool: finish: PATH="/usr/bin:/cshome/will/apache-maven-3.2.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/aws/bin:/sbin" ldconfig -n /cshome/will/pdo_snowflake/modules
----------------------------------------------------------------------
Libraries have been installed in:
   /cshome/will/pdo_snowflake/modules

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the `LD_RUN_PATH' environment variable
     during linking
   - use the `-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to `/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------

Build complete.
Don't forget to run 'make test'.

libtool: install: cp ./.libs/pdo_snowflake.so /cshome/will/pdo_snowflake/modules/pdo_snowflake.so
libtool: install: cp ./.libs/pdo_snowflake.lai /cshome/will/pdo_snowflake/modules/pdo_snowflake.la
libtool: finish: PATH="/usr/bin:/cshome/will/apache-maven-3.2.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/aws/bin:/sbin" ldconfig -n /cshome/will/pdo_snowflake/modules
----------------------------------------------------------------------
Libraries have been installed in:
   /cshome/will/pdo_snowflake/modules

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the `LD_RUN_PATH' environment variable
     during linking
   - use the `-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to `/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
```

**Comment by jawwadsyed512** [comment]
I am also facing the same issue!

As suggested by another user who faced this issue, modifying the linker as below made it work.

Can this be fixed in the build please?

cc -shared -fPIC -DPIC .libs/pdo_snowflake.o .libs/snowflake_driver.o .libs/snowflake_stmt.o .libs/snowflake_arraylist.o libsnowflakeclient/lib/linux/libsnowflakeclient.a libsnowflakeclient/deps-build/linux/openssl/lib/libcrypto.a libsnowflakeclient/deps-build/linux/openssl/lib/libssl.a libsnowflakeclient/deps-build/linux/curl/lib/libcurl.a libsnowflakeclient/deps-build/linux/aws/lib64/libaws-cpp-sdk-core.a libsnowflakeclient/deps-build/linux/aws/lib64/libaws-cpp-sdk-s3.a libsnowflakeclient/deps-build/linux/azure/lib/libazure-storage-lite.a -O2 -Wl,--whole-archive -Wl,--no-whole-archive -Wl,-soname -Wl,pdo_snowflake.so -o .libs/pdo_snowflake.so libsnowflakeclient/deps-build/linux/openssl/lib/libssl.a libsnowflakeclient/deps-build/linux/openssl/lib/libcrypto.a libsnowflakeclient/deps-build/linux/cmocka/lib/libcmocka.a

**Comment by notkriswagner** [comment]
@oberman and @jawwadsyed512 I've updated the build script to fix this issue in the latest release v0.2.4. Let me know if either of you are still experiencing issues.

**Comment by zoltan-fedor** [comment]
@notkriswagner - I don't know about the other, but I have just faced the same issues as described above and your fix did NOT solve it. I had to use the above command from @jawwadsyed512 to modify the linker to make this error go away.

**Comment by notkriswagner** [comment]
@zoltan-fedor I copied the above command and put that in the build script, let me investigate this issue some more

**Comment by hcira** [comment]
@notkriswagner is there any update on this? we're also facing the same issue.
Thanks!

**Comment by plsoucy-tapclicks** [comment]
Any update on this? Thanks!

**Comment by zoltan-fedor** [comment]
Any update on this? The issue is still there with code cloned today.

**Comment by hcira** [comment]
found that $PLATFORM variable was not set in the build script  and as a result, the module was not compiled.
I added `export PLATFORM=$(uname -a | awk '{print tolower($1)}')` and the SO work fine

**Comment by notkriswagner** [comment]
Yes, it looks like the init script is never called in the build script. I've created #210 to fix this

**Comment by notkriswagner** [comment]
This is fixed in v0.2.5. @zoltan-fedor can you confirm this fixes your issue?

**Comment by zoltan-fedor** [comment]
@notkriswagner, I have tested it and it compiles now correctly.
Thanks for fixing this!
